name: CMake
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: make build directory
      run: cd ${{github.workspace}} && mkdir build

    - name: Install ninja-build tool
      run: sudo apt-get update && sudo apt-get install -y ninja-build

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DLLVM_PARALLEL_LINK_JOBS=2 -DLLVM_USE_LINKER=gold

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --target build-all
