name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make build directory
      run: cd ${{github.workspace}} && mkdir build
    
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --target all

      
