name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make build directory
      run: cd ${{github.workspace}} && mkdir build
    
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --target build-all
  
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@master
    
    - name: Publish Doxygen documentation
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - docs/html/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
