name: CMake

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make build directory
      run: cd ${{github.workspace}} && mkdir build
    
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --target build-all
  
  release:  
    name: Upload release documentation
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: docs/html/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
